### ISSUE TITLE
feature request: allow skipping repositories instead of stopping

### ISSUE THREAD

**Issue by IamShobe** [ilaif/goplicate#16]
Hi there again :) 
I would like the tool to do the "best effort" - and not stop all operation on the first `N` I insert.
a suggestion will be to do something more like `git add -p` - to have 3 operations:
```
Yes No Quit
```

if I choose Yes will apply the change.
if I choose No will skip to the next one
Quite to allow quitting (can also be done with Ctrl + c so maybe it's redundent).

**Comment by ilaif** [comment]
Hi @IamShobe ^^
Please see https://github.com/ilaif/goplicate/pull/18

**Comment by ilaif** [comment]
Resolved in #18
